version: "3"

services:

  application:
    restart: unless-stopped
    ports:
      - "80:3000"
    build:
      context: .
    environment:
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
