name: nodejs CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.14.2
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2

      # Install locked dependencies and prepare types
      - run: npm ci

      # Check building
      - run: npm run build

      # start dev-app and curl from it
      - run: "timeout 30 npm run dev & (sleep 10 && curl --fail localhost:3000)"

      # start prod-app and curl from it
      - run: "timeout 30 npm run start & (sleep 10 && curl --fail localhost:3000)"
